import {
  Illus2FA,
  IllusAddAccount,
  IllusChecked,
  IllusEmailError,
  IllusError,
  IllusID,
  IllusLinkExpired,
  IllusLocked,
  IllusPasskey,
  IllusPending,
  IllusRegionNotSupported,
  IllusVerification,
} from './illustration-set';
import {
  Logo,
  LogoBg,
  LogoBeta,
  LogoNetwork,
  LogoWithBeta,
  LogoWithWords,
  LogoWord,
} from './logos';
import {
  ACHIcon,
  APIKeyIcon,
  AccountIcon,
  AccountLockedIcon,
  AddIcon,
  AddressBookIcon,
  AppleIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  ArrowRightIcon,
  AutoConversionRulesIcon,
  BankIcon,
  BrokenLinkIcon,
  BurnTokenIcon,
  BusinessAccountIcon,
  CalendarIcon,
  CardIcon,
  ChatIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  ClockIcon,
  CollapseIcon,
  CoinIcon,
  CoinsIcon,
  CompanyIcon,
  ConversionIcon,
  ConvertIcon,
  CopyIcon,
  CNYIcon,
  DashboardIcon,
  DesktopIcon,
  DevicesIcon,
  DigitalAssetIcon,
  DislikeIcon,
  DocumentIcon,
  EarnIcon,
  EditFileIcon,
  EmailIcon,
  EURIcon,
  ExpandIcon,
  ExtendIcon,
  FailIcon,
  FavoriteIcon,
  FeesIcon,
  FiatIcon,
  FilterIcon,
  GBPIcon,
  GiftIcon,
  GoogleIcon,
  HelpIcon,
  HomeIcon,
  HubIcon,
  IDIcon,
  ImagesIcon,
  IndividualAccountIcon,
  InfoIcon,
  JPYIcon,
  LanguageIcon,
  LikeIcon,
  LinkIcon,
  LinkedBankAccountsIcon,
  LocationIcon,
  LogoutIcon,
  MaintenanceIcon,
  MenuDepositIcon,
  MinusIcon,
  MintTokenIcon,
  MobileIcon,
  MoneyIcon,
  MoreIcon,
  NotificationsIcon,
  PartiesIcon,
  PasskeyIcon,
  PauseIcon,
  PendingIcon,
  PixIcon,
  PortfolioIcon,
  PrivacyIcon,
  ProductsIcon,
  ProfileIcon,
  RefreshIcon,
  RemoveIcon,
  RewardsIcon,
  SaveIcon,
  ScanIcon,
  SecurityCheckIcon,
  SecurityIcon,
  SendCryptoIcon,
  SendIcon,
  SettingsIcon,
  ShareIcon,
  SortIcon,
  SpinnerIcon,
  StatusFailIcon,
  StatusSuccessIcon,
  SuccessIcon,
  SupportIcon,
  SwapIcon,
  SWIFTIcon,
  SystemCollapseIcon,
  SystemSecurityIcon,
  TimeIcon,
  TransactionsIcon,
  TransferHistoryIcon,
  TransferIcon,
  TwitterIcon,
  USDIcon,
  WithdrawalIcon,
  WalletIcon,
  WireIcon,
  WithdrawIcon,
  LinkedInIcon,
  DepositIcon,
} from './SVGs';
import {
  ArrowLeftIcon,
  CheckIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  CrossIcon,
  ErrorIcon,
  HideBalanceIcon,
  NotificationErrorIcon,
  NotificationInfoIcon,
  NotificationSuccessIcon,
  NotificationWarningIcon,
  SearchIcon,
  UploadIcon,
  ViewBalanceIcon,
} from './static-icons';

export const iconRegistry = {
  illusChecked: IllusChecked,
  illusEmailError: IllusEmailError,
  illusLinkExpired: IllusLinkExpired,
  illus2FA: Illus2FA,
  illusLocked: IllusLocked,
  illusError: IllusError,
  illusRegionNotSupported: IllusRegionNotSupported,
  illusID: IllusID,
  illusVerification: IllusVerification,
  illusPasskey: IllusPasskey,
  illusAddAccount: IllusAddAccount,
  illusPending: IllusPending,
  logo: Logo,
  logoWord: LogoWord,
  logoNetwork: LogoNetwork,
  logoWithWords: LogoWithWords,
  logoBg: LogoBg,
  logoBeta: LogoBeta,
  logoWithBeta: LogoWithBeta,
  deposit: DepositIcon,
  withdrawal: WithdrawalIcon,
  conversion: ConversionIcon,
  mintToken: MintTokenIcon,
  burnToken: BurnTokenIcon,
  accountLocked: AccountLockedIcon,
  pending: PendingIcon,
  success: SuccessIcon,
  fail: FailIcon,
  error: ErrorIcon,
  statusSuccess: StatusSuccessIcon,
  statusFail: StatusFailIcon,
  dashboard: DashboardIcon,
  digitalAsset: DigitalAssetIcon,
  addressBook: AddressBookIcon,
  linkedBankAccounts: LinkedBankAccountsIcon,
  wire: WireIcon,
  swift: SWIFTIcon,
  account: AccountIcon,
  profile: ProfileIcon,
  security: SecurityIcon,
  logout: LogoutIcon,
  portfolio: PortfolioIcon,
  home: HomeIcon,
  convert: ConvertIcon,
  withdraw: WithdrawIcon,
  send: SendIcon,
  menuDeposit: MenuDepositIcon,
  company: CompanyIcon,
  parties: PartiesIcon,
  transactions: TransactionsIcon,
  fiat: FiatIcon,
  money: MoneyIcon,
  sendCrypto: SendCryptoIcon,
  arrowUp: ArrowUpIcon,
  arrowDown: ArrowDownIcon,
  arrowLeft: ArrowLeftIcon,
  arrowRight: ArrowRightIcon,
  add: AddIcon,
  minus: MinusIcon,
  cross: CrossIcon,
  more: MoreIcon,
  chevronDown: ChevronDownIcon,
  chevronUp: ChevronUpIcon,
  chevronLeft: ChevronLeftIcon,
  chevronRight: ChevronRightIcon,
  sort: SortIcon,
  collapse: CollapseIcon,
  extend: ExtendIcon,
  spinner: SpinnerIcon,
  check: CheckIcon,
  remove: RemoveIcon,
  pix: PixIcon,
  info: InfoIcon,
  notifications: NotificationsIcon,
  favorite: FavoriteIcon,
  transferHistory: TransferHistoryIcon,
  support: SupportIcon,
  help: HelpIcon,
  language: LanguageIcon,
  share: ShareIcon,
  products: ProductsIcon,
  hub: HubIcon,
  systemSecurity: SystemSecurityIcon,
  fees: FeesIcon,
  settings: SettingsIcon,
  id: IDIcon,
  viewBalance: ViewBalanceIcon,
  hideBalance: HideBalanceIcon,
  privacy: PrivacyIcon,
  card: CardIcon,
  coin: CoinIcon,
  wallet: WalletIcon,
  email: EmailIcon,
  rewards: RewardsIcon,
  time: TimeIcon,
  location: LocationIcon,
  calendar: CalendarIcon,
  securityCheck: SecurityCheckIcon,
  devices: DevicesIcon,
  images: ImagesIcon,
  bank: BankIcon,
  coins: CoinsIcon,
  earn: EarnIcon,
  scan: ScanIcon,
  search: SearchIcon,
  maintenance: MaintenanceIcon,
  editFile: EditFileIcon,
  document: DocumentIcon,
  upload: UploadIcon,
  gift: GiftIcon,
  filter: FilterIcon,
  expand: ExpandIcon,
  systemCollapse: SystemCollapseIcon,
  refresh: RefreshIcon,
  transfer: TransferIcon,
  link: LinkIcon,
  save: SaveIcon,
  like: LikeIcon,
  dislike: DislikeIcon,
  copy: CopyIcon,
  mobile: MobileIcon,
  chat: ChatIcon,
  swap: SwapIcon,
  clock: ClockIcon,
  desktop: DesktopIcon,
  ach: ACHIcon,
  businessAccount: BusinessAccountIcon,
  individualAccount: IndividualAccountIcon,
  apiKey: APIKeyIcon,
  brokenLink: BrokenLinkIcon,
  autoConversionRules: AutoConversionRulesIcon,
  usd: USDIcon,
  eur: EURIcon,
  gbp: GBPIcon,
  jpy: JPYIcon,
  cny: CNYIcon,
  google: GoogleIcon,
  apple: AppleIcon,
  twitter: TwitterIcon,
  linkedIn: LinkedInIcon,
  passkey: PasskeyIcon,
  pause: PauseIcon,
  notificationInfo: NotificationInfoIcon,
  notificationWarning: NotificationWarningIcon,
  notificationSuccess: NotificationSuccessIcon,
  notificationError: NotificationErrorIcon,
} as const;
